import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Todo list',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className="flex h-full min-h-screen  items-center justify-center"
    >
      <body
        className={`${inter.className} relative flex h-full w-full flex-1 items-center justify-center bg-zinc-900`}
      >
        {children}
      </body>
    </html>
  )
}
